### ISSUE TITLE
某些网址用字很难手工打出来 

### ISSUE THREAD

**Issue by nimingzhe7** [chenxuuu/shit-url#1]
生成的网址非常短 , 很有创意 
但也有一个令人头疼的原生缺陷 , 就是生成的网址所用汉字有大部分相当生僻 , 假如在不能复制粘贴的场合 , 需要手工输入的话 就会非常困难 或者几乎不可能 正确输入 , 这种潜在的风险 使人倾向于在重要场合 不敢使用 , 非常可惜

**Comment by chenxuuu** [comment]
本网址的目标就是让人打不出来
